### PR TITLE
fix: download runtime to private cache for flatpak

### LINKED ISSUE #219: [flatpak] Invalid cross-device link
a `Invalid cross-device link` error pops up when trying to use the umu-launcher (https://github.com/Open-Wine-Components/umu-launcher/commit/cfe955f42b0fed574fd1f5bc4165f7491a775c25) via flatpak on a freshly installed Fedora 41, Flatpak 1.15.10 system.

this issue might be specific to umu-launcher being installed as a system instead of a user app.

```
$ git clone https://github.com/Open-Wine-Components/umu-launcher.git
$ cd umu-launcher/packaging/flatpak
$ sudo flatpak-builder --force-clean --install-deps-from=flathub --repo=umu-repo --install umu-launcher org.openwinecomponents.umu.umu-launcher.yml
$ flatpak run --env=GAMEID=UNKNOWN --env=WINEPREFIX=[some_prefix_path] org.openwinecomponents.umu.umu-launcher [some_exe_path]
Setting up Unified Launcher for Windows Games on Linux...
UMU-Proton is up to date
Downloading latest steamrt sniper, please wait...
SteamLinuxRuntime_sniper.tar.xz: SHA256 is OK
Traceback (most recent call last):
  File "/usr/lib/python3.11/shutil.py", line 853, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/var/home/mershl/.cache/umu/tmpl3j1fb5i/SteamLinuxRuntime_sniper/pressure-vessel' -> '/var/home/mershl/.var/app/org.openwinecomponents.umu.umu-launcher/data/umu/pressure-vessel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/umu-run", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/umu/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/app/lib/python3.11/site-packages/umu/umu_run.py", line 829, in main
    future.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/umu/umu_runtime.py", line 204, in setup_umu
    _restore_umu(
  File "/app/lib/python3.11/site-packages/umu/umu_runtime.py", line 515, in _restore_umu
    _install_umu(json, thread_pool, client_session)
  File "/app/lib/python3.11/site-packages/umu/umu_runtime.py", line 177, in _install_umu
    future.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/umu/umu_runtime.py", line 453, in _move
    move(src_file, dest_file)
  File "/usr/lib/python3.11/shutil.py", line 869, in move
    copytree(src, real_dst, copy_function=copy_function,
  File "/usr/lib/python3.11/shutil.py", line 573, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shutil.py", line 527, in _copytree
    raise Error(errors)
shutil.Error: [('/var/home/mershl/.cache/umu/tmpl3j1fb5i/SteamLinuxRuntime_sniper/pressure-vessel/bin/pressure-vessel-locale-gen', .................]
```

### PR DESCRIPTION
**Pull request by R1kaB3rN**
Fixes https://github.com/Open-Wine-Components/umu-launcher/issues/219

### CODE REVIEW

**Comment by zocker-160** [comment]
I think it would be better to use `XDG_CACHE_HOME` instead. 
Inside Flatpak this resolves to the same path that you are hardcoding right now, which is `/home/USER/.var/app/APPID/cache` and use the default path when not set.

**Comment by R1kaB3rN** [comment]
The problem with $XDG_CACHE_HOME is that we could be downloading to a client's private Flatpak cache directory. For instance, Heroic and Lutris sources umu-launcher in its runtime and when they call umu-run, the value of $XDG_CACHE_HOME will be Heroic's instead of umu-launcher. This could cause the runtime to be downloaded there, which is not what we want. We want to centralize all Steam Runtime installations in a single place, so there isn't runtimes everywhere.

**Comment by zocker-160** [comment]
@R1kaB3rN but isn't that actually desirable? 

When I use lutris Flatpak, the folder it tries to access `.var/app/org.openwinecomponents.umu.umu-launcher` does not exist.

Do the default permissions even allow to create and write to that folder?

> We want to centralize all Steam Runtime installations in a single place, so there isn't runtimes everywhere.

I don't think this is possible with the current permissions.

**Comment by zocker-160** [comment]
seems like I can write to that folder, but it is not persisting, I feel like this could cause issues.
```
$ flatpak run --command=sh net.lutris.Lutris 
[📦 net.lutris.Lutris ~]$ mkdir .var/app/org.openwinecomponents.umu.umu-launcher
[📦 net.lutris.Lutris ~]$ echo "test" > .var/app/org.openwinecomponents.umu.umu-launcher/test
[📦 net.lutris.Lutris ~]$ cat .var/app/org.openwinecomponents.umu.umu-launcher/test 
test
[📦 net.lutris.Lutris ~]$ exit
$ flatpak run --command=sh net.lutris.Lutris 
[📦 net.lutris.Lutris ~]$ cat .var/app/org.openwinecomponents.umu.umu-launcher/test
cat: .var/app/org.openwinecomponents.umu.umu-launcher/test: No such file or directory
[📦 net.lutris.Lutris ~]$ 
```

**Comment by Mershl** [comment]
see https://github.com/flathub/net.lutris.Lutris/issues/440#issuecomment-2408767641
a short-term workaround has been implemented in flatpak lutris

**Pull request merged**
