### PR TITLE
Add bwrap apparmor profile to debian packaging

### PR DESCRIPTION
**Pull request by CosmicFusion**

### CODE REVIEW

**Comment by darix** [comment]
JFYI: i discussed this apparmor profile with the openSUSE apparmor maintainer. profiles like this were requested upstream multiple times and rejected.

in the mean time they added apparmor/profiles/extras/bwrap-userns-restrict which limits what bwrap started programs can do afterwards. 

so instead of copying a custom profile in, why not just enable that extra profile by packaging the needed symlink?

**Comment by GloriousEggroll** [comment]
> JFYI: i discussed this apparmor profile with the openSUSE apparmor maintainer. profiles like this were requested upstream multiple times and rejected.
> 
> in the mean time they added apparmor/profiles/extras/bwrap-userns-restrict which limits what bwrap started programs can do afterwards.
> 
> so instead of copying a custom profile in, why not just enable that extra profile by packaging the needed symlink?

if it works it's more than welcome, feel free to make a PR. we simply were going based off results from this bug: https://github.com/Open-Wine-Components/umu-launcher/issues/210

I'm also not sure if that profile is included in ubuntu

**Comment by darix** [comment]
the bwrap-userns-restrict profile might even be shipped in ubuntu but not turned on by default (as it is an extra profile)

I am not author of https://gitlab.com/apparmor/apparmor/-/blob/master/profiles/apparmor/profiles/extras/bwrap-userns-restrict?ref_type=heads 

but i can ask if they are fine with including the profile in umu-launcher. (gpl2 vs gpl3)

**Comment by darix** [comment]
apparmor upstream suggested a better solution might be to apparmor profile the scripts that call bwrap in the umu scope and then you have full control about what the bwrap in the scope of umu should be able to do without affecting other tools like flatpak system wide. 

thoughts?

**Pull request merged**
