### PR TITLE
gamelauncher: convert to posix sh.

### PR DESCRIPTION
**Pull request by sewnie**
untested, PR made so i can be able to test https://github.com/vinegarhq/vinegar/issues/356

### CODE REVIEW

**Comment by sewnie** [comment]
@GloriousEggroll why did you steal code from this PR and not credit me as an author?

**Comment by sewnie** [comment]
You're still using bad shell practices and not using `shellcheck`.

**Comment by GloriousEggroll** [comment]
Since you want to go down this rabbit hole, pasting from my previous comment:

> This is broken. Which my pr #12 solves, which was stolen.
> 
> This is going to run in a seperate shell and will not declare variables.
> 
> ```
> $ echo meow | while read -r line; do meow=true; done
> $ echo $meow
> 
> $ 
> ```
> 
> Good job.

excuse me? I didn't "steal" anything.  I quite literally went through the script using https://www.shellcheck.net and https://www.phind.com to correct things. I don't mind correcting errors, noone is perfect, but accusation of stealing is really not appropriate, nor is the sarcasm.

I didn't even LOOK at your PR because I wanted to go through the script myself to see what needed to be changed. This comment is incredibly rude.

I converted the script for your benefit in the first place, I could have just as easily said no. 

My original script was freehand coded -- so no, I did not use shell check for the original bash script because I know how to code bash. Was it perfect? no, but it worked.  I do not know pure posix as well as bash, so I used shellcheck and phind for converting to posix. 

You really need to learn to communicate respectfully with other projects and not outright accuse people.

**Comment by GloriousEggroll** [comment]
And since we're at it, let's get a couple things straight here:

1. YOU came to MY discord asking for help since I ported ULWGL over to grapejuice
2. YOU asked for a flatpak or native musl check because YOU needed it for YOUR system, which I spent time cranking the flatpak out on AFTER you asked me for an ETA on a free-time based project's flatpak, I said ok, I need to do that anyway.
3. YOU asked for POSIX when noone else needed it. I saw the issue subject come up in my email and said ok, simple enough.
4. THEN you accuse me of stealing code because we both used shellcheck for making the same fixes, knowing well I have been doing this for several years and have been more than happy to give credit to people who have committed changes that I did not write. This was not the case. We had the same changes coincidentally from using shellcheck. That's it.

Now, let me know if you want to try being a reasonable person and act like an adult, or whether I should stop helping you here and now.

-edit- 
It was lunarlettuce who came into my discord and asked for help + asked for flatpak ETA -- apologies, I thought you were the same person. My point remains the same, if I'd used your code I would have credited you, hell I would have merged the PR, but like I said, I didn't even look at it. I saw the subject come via email and that was it.

**Comment by sewnie** [comment]
Okay then. Next time, tell a contributor this instead of just abruptly closing the PR.

**Comment by GloriousEggroll** [comment]
> Okay then. Next time, tell a contributor this instead of just abruptly closing the PR.

When you submit a git commit and tag an issue link in it, it automatically closes the PR

Stop being an asshole.

**Pull request closed without merging**
